# Generated by Django 4.1.5 on 2023-01-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_title', models.CharField(max_length=255)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('product_blog', models.TextField()),
                ('product_capacity', models.CharField(max_length=255)),
                ('product_compatibility', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255, null=True)),
                ('Product_speed', models.IntegerField()),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.subcategory')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcolor')),
                ('product_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productimage')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='niche_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.niche'),
        ),
    ]
