# Generated by Django 4.1.5 on 2023-01-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='niche_id',
            new_name='niche',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='niche',
            name='niche_title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
