# Generated by Django 4.1.5 on 2023-02-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_affiliate_link',
            new_name='product_link',
        ),
    ]
