# Generated by Django 4.1.5 on 2023-02-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvideo',
            old_name='image_url',
            new_name='video_url',
        ),
    ]
