# Generated by Django 4.1.5 on 2023-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
