# Generated by Django 4.1.5 on 2023-01-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.AddField(
            model_name='product',
            name='product_discount_price',
            field=models.DecimalField(decimal_places=2, default=22.3, max_digits=6),
            preserve_default=False,
        ),
    ]
