# Generated by Django 4.1.5 on 2023-01-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_options_product_product_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_speed',
            new_name='product_speed',
        ),
    ]
