# Generated by Django 4.1.6 on 2023-02-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productquestions_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquestions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
            preserve_default=False,
        ),
    ]
